package 安卓x.组合.材质3.令牌集

internal object ElevatedButtonTokens {
    val ContainerColor = ColorSchemeKeyTokens.SurfaceContainerLow
    val ContainerElevation = ElevationTokens.Level1
    val DisabledContainerColor = ColorSchemeKeyTokens.OnSurface
    val DisabledContainerElevation = ElevationTokens.Level0
    val DisabledContainerOpacity = 0.1f
    val DisabledIconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val DisabledIconOpacity = 0.38f
    val DisabledLabelTextColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val DisabledLabelTextOpacity = 0.38f
    val FocusedContainerElevation = ElevationTokens.Level1
    val FocusedIconColor = ColorSchemeKeyTokens.Primary
    val FocusedLabelTextColor = ColorSchemeKeyTokens.Primary
    val HoveredContainerElevation = ElevationTokens.Level2
    val HoveredIconColor = ColorSchemeKeyTokens.Primary
    val HoveredLabelTextColor = ColorSchemeKeyTokens.Primary
    val IconColor = ColorSchemeKeyTokens.Primary
    val LabelTextColor = ColorSchemeKeyTokens.Primary
    val LabelTextSelectedColor = ColorSchemeKeyTokens.OnPrimary
    val LabelTextUnselectedColor = ColorSchemeKeyTokens.Primary
    val PressedContainerElevation = ElevationTokens.Level1
    val PressedIconColor = ColorSchemeKeyTokens.Primary
    val PressedLabelTextColor = ColorSchemeKeyTokens.Primary
    val SelectedContainerColor = ColorSchemeKeyTokens.Primary
    val SelectedFocusedIconColor = ColorSchemeKeyTokens.OnPrimary
    val SelectedFocusedLabelTextColor = ColorSchemeKeyTokens.OnPrimary
    val SelectedHoveredIconColor = ColorSchemeKeyTokens.OnPrimary
    val SelectedHoveredLabelTextColor = ColorSchemeKeyTokens.OnPrimary
    val SelectedIconColor = ColorSchemeKeyTokens.OnPrimary
    val SelectedPressedIconColor = ColorSchemeKeyTokens.OnPrimary
    val SelectedPressedLabelTextColor = ColorSchemeKeyTokens.OnPrimary
    val UnselectedContainerColor = ColorSchemeKeyTokens.SurfaceContainerLow
    val UnselectedFocusedIconColor = ColorSchemeKeyTokens.Primary
    val UnselectedFocusedLabelTextColor = ColorSchemeKeyTokens.Primary
    val UnselectedHoveredIconColor = ColorSchemeKeyTokens.Primary
    val UnselectedHoveredLabelTextColor = ColorSchemeKeyTokens.Primary
    val UnselectedIconColor = ColorSchemeKeyTokens.OnPrimary
    val UnselectedPressedIconColor = ColorSchemeKeyTokens.Primary
    val UnselectedPressedLabelTextColor = ColorSchemeKeyTokens.Primary
}
