package 安卓x.组合.材质3.令牌集

internal object FilledButtonTokens {
    val ContainerColor = ColorSchemeKeyTokens.Primary
    val ContainerElevation = ElevationTokens.Level0
    val DisabledContainerColor = ColorSchemeKeyTokens.OnSurface
    val DisabledContainerElevation = ElevationTokens.Level0
    val DisabledContainerOpacity = 0.1f
    val DisabledIconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val DisabledIconOpacity = 0.38f
    val DisabledLabelTextColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val DisabledLabelTextOpacity = 0.38f
    val FocusedContainerElevation = ElevationTokens.Level0
    val FocusedIconColor = ColorSchemeKeyTokens.OnPrimary
    val FocusedLabelTextColor = ColorSchemeKeyTokens.OnPrimary
    val HoveredContainerElevation = ElevationTokens.Level1
    val HoveredIconColor = ColorSchemeKeyTokens.OnPrimary
    val HoveredLabelTextColor = ColorSchemeKeyTokens.OnPrimary
    val IconColor = ColorSchemeKeyTokens.OnPrimary
    val LabelTextColor = ColorSchemeKeyTokens.OnPrimary
    val LabelTextSelectedColor = ColorSchemeKeyTokens.OnPrimary
    val LabelTextUnselectedColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val PressedContainerElevation = ElevationTokens.Level0
    val PressedIconColor = ColorSchemeKeyTokens.OnPrimary
    val PressedLabelTextColor = ColorSchemeKeyTokens.OnPrimary
    val SelectedContainerColor = ColorSchemeKeyTokens.Primary
    val SelectedFocusedIconColor = ColorSchemeKeyTokens.OnPrimary
    val SelectedFocusedLabelTextColor = ColorSchemeKeyTokens.OnPrimary
    val SelectedHoveredIconColor = ColorSchemeKeyTokens.OnPrimary
    val SelectedHoveredLabelTextColor = ColorSchemeKeyTokens.OnPrimary
    val SelectedIconColor = ColorSchemeKeyTokens.OnPrimary
    val SelectedPressedIconColor = ColorSchemeKeyTokens.OnPrimary
    val SelectedPressedLabelTextColor = ColorSchemeKeyTokens.OnPrimary
    val UnselectedContainerColor = ColorSchemeKeyTokens.SurfaceContainer
    val UnselectedFocusedIconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val UnselectedFocusedLabelTextColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val UnselectedHoveredIconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val UnselectedHoveredLabelTextColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val UnselectedIconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val UnselectedPressedIconColor = ColorSchemeKeyTokens.OnSurfaceVariant
    val UnselectedPressedLabelTextColor = ColorSchemeKeyTokens.OnSurfaceVariant
}
